<?php

/**
 * @file
 * Contains event_brite.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function event_brite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the event_brite module.
    case 'help.page.event_brite':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integration with event brite platform') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function event_brite_theme($existing, $type, $theme, $path) {
  return 
    [
      'event_brite' => [
        'render element' => 'children',
      ],
      'nextevents' => [
        'render element' => 'elements',
        'variables' => array( 'events' => array() ),
        'template' => 'block--next-events'
      ]
    ];
}
