<?php

/**
 * @file
 * Contains migracion_colombiatravel.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;


/**
 * Implements hook_help().
 */
function migracion_colombiatravel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migracion_colombiatravel module.
    case 'help.page.migracion_colombiatravel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Modulo de migracion para procolombia') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_migrate_prepare_row
 */ 

 function migracion_colombiatravel_migrate_drupal_activities_prepare_row(Row $row, MigrateSourceInterface $source, $migration){
    // var_dump($migration->id());
    var_dump($row->getSourceProperty('nid'));
    $value = $source
      ->getDatabase()
      ->query('SELECT data FROM {metatag} WHERE entity_id = :nid', [
      ':nid' => $row->getSourceProperty('nid'),
      ])
      ->fetchField();
    if ($value) {
      $row->setSourceProperty('field_metatags', $value);
    }
 }


 function migracion_colombiatravel_migrate_drupal_articles_prepare_row(Row $row, MigrateSourceInterface $source, $migration){
  // var_dump($migration->id());
  var_dump($row->getSourceProperty('nid'));
  $value = $source
    ->getDatabase()
    ->query('SELECT data FROM {metatag} WHERE entity_id = :nid', [
    ':nid' => $row->getSourceProperty('nid'),
    ])
    ->fetchField();
  if ($value) {
    $row->setSourceProperty('field_metatags', $value);
  }
}