<?php

/**
 * @file
 * Contains user_preferences.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_preferences_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_preferences module.
    case 'help.page.user_preferences':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User preference by taxonomy') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_preferences_theme() {
  return [
    'user_preferences' => [
      'render element' => 'children',
    ],
    'activity_block' => [
      'variables' => [
        'list_activity' => NULL
      ],
      'template' => 'activity-block',
    ],
  ];
}
